### ISSUE TITLE
Multiple dependsOn subkeys are not kept

### ISSUE THREAD

**Issue by sebbalex** [italia/publiccode-parser-go#20]
When submitting a publiccode which have multiple key for a given type it keeps and exports only the last one. See below:
in:
```
dependsOn:
  open:
    - name: MySQL
      versionMin: "1.1"
      versionMax: "1.3"
      optional: true
    - name: PostgreSQL
      version: "3.2"
      optional: true
```

out:
```
dependsOn:
  open:
  - name: PostgreSQL
    versionMin: ""
    versionMax: ""
    optional: true
    version: "3.2"
```
