### ISSUE TITLE
Incorrect Maintenance field validation

### ISSUE THREAD

**Issue by valeriocomo** [italia/publiccode-parser-go#206]
## Description

The validator try to validate the subfield _contacts_ or _contractors_ when should not be present.

### Payload example

```yml
maintenance:
  type: "community"
  
  # Should NOT validate contractors
  contractors:
    - name: "Fornitore Privato SPA"
      website: "https://developers.italia.it"
      #until: "2019-01-01"

  contacts:
    - name: Francesco Rossi
```
If this payload would be submitted, the validator will fail because a contractor item is not valid (_until_ field is mandatory and must be defined). But, It must not be validated because field type value isn't set to _contract_.
The same behaviour applies in the case where _type_ is set to _contract_ and there are occurrences of _contacts_.

## Step to reproduce

Validate a _publiccode.yml_ with a payload formed like the one described above.

## Expected behaviour

Should return an error because there are occurrences of contractors/contacts when the value of type isn't set accordingly, IMHO.
@bfabio @tensor5 your opinions are welcome.

## Actual behaviour

It returns an error because an occurrence of contractors/contacts is not valid (as stated in the description).
